ci: update to kilted

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,34 +1,68 @@
 name: Tag & Release
-
 on:
   workflow_dispatch:
+    inputs:
+      build_kilted:
+        type: boolean
+        default: true
+        description: "Release for Kilted"
+      build_jazzy:
+        type: boolean
+        default: true
+        description: "Release for Jazzy"
 
 jobs:
-  release:
+  setup:
+    runs-on: ubuntu-latest
+    outputs:
+      distros: ${{ steps.set-distros.outputs.distros }}
+    steps:
+      - id: set-distros
+        run: |
+          distros=()
+          [ "${{ github.event.inputs.build_jazzy }}" == "true" ] && distros+=("jazzy")
+          [ "${{ github.event.inputs.build_kilted }}" == "true" ] && distros+=("kilted")
+
+          if [ ${#distros[@]} -eq 0 ]; then
+            echo "::error::No distros selected. Please enable release for at least one of the available distros."
+            exit 1
+          fi
+
+          echo "distros=$(jq -cn '$ARGS.positional' --args "${distros[@]}")" >> $GITHUB_OUTPUT
+  build:
+    needs: setup
     strategy:
       fail-fast: true
       matrix:
+        distro: ${{ fromJson(needs.setup.outputs.distros) }}
         job:
-          - runner: buildjet-4vcpu-ubuntu-2204
+          - runner: 4vcpu-ubuntu-2404
             arch: amd64
-            ros_distro: iron
-            github_release: true
-          - runner: buildjet-4vcpu-ubuntu-2204-arm
+          - runner: 4vcpu-ubuntu-2404-arm
             arch: arm64
-            ros_distro: iron
-            github_release: false
-          - runner: buildjet-4vcpu-ubuntu-2204
-            arch: amd64
-            ros_distro: jazzy
-            github_release: false
-          - runner: buildjet-4vcpu-ubuntu-2204-arm
-            arch: arm64
-            ros_distro: jazzy
-            github_release: false
+    name: Build - ${{ matrix.job.arch }} - ${{ matrix.distro }}
+    runs-on: ${{ matrix.job.runner }}
 
-    name: Release - ${{ matrix.job.arch }}
-    runs-on: ${{matrix.job.runner}}}
+    steps:
+      - name: Checkout this repository
+        uses: actions/checkout@v4
 
+      - name: Semantic release - Build
+        uses: Greenroom-Robotics/ros_semantic_release_action@main
+        with:
+          token: ${{ secrets.API_TOKEN_GITHUB }}
+          arch: ${{ matrix.job.arch }}
+          ros_distro: ${{ matrix.distro }}
+          github_release: false
+          public: false
+          changelog: false
+          skip_build: false
+          skip_tag: true
+
+  release:
+    name: Create Release
+    needs: build
+    runs-on: 2vcpu-ubuntu-2404
     steps:
       - name: Checkout this repository
         uses: actions/checkout@v3
@@ -37,8 +71,8 @@ jobs:
         uses: Greenroom-Robotics/ros_semantic_release_action@main
         with:
           token: ${{ secrets.API_TOKEN_GITHUB }}
-          arch: ${{ matrix.job.arch }}
-          ros_distro: ${{ matrix.job.ros_distro }}
-          github_release: ${{ matrix.job.github_release }}
-          public: true
+          github_release: true
+          public: false
           changelog: false
+          skip_build: true
+          skip_tag: false
